version: "3.8"

services:
  # --- 1. DATABASE SERVICE ---
  db_service:
    image: mysql:8.0
    container_name: db_${GROUP_NAME}
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      # PENTING: Agar data tidak hilang saat container dimatikan
      - mysql_data:/var/lib/mysql
      # Load file init.sql agar tabel & data dummy otomatis dibuat
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app_network

  # --- 2. APP SERVICE ---
  app_service:
    build: ./app
    container_name: app_${GROUP_NAME}
    restart: always
    expose:
      - "3000"
    environment:
      - DB_HOST=db_service
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_NAME=${DB_NAME}
      - APP_PORT=3000
    depends_on:
      - db_service
    volumes:
      # Mount folder codingan agar bisa edit live
      - ./app:/usr/src/app
      # Trik agar node_modules di container tidak tertimpa/konflik dengan laptop
      - /usr/src/app/node_modules
    networks:
      - app_network

  # --- 3. NGINX SERVICE ---
  nginx_service:
    image: nginx:alpine
    container_name: nginx_${GROUP_NAME}
    restart: always
    ports:
      - "${APP_PORT}:80"
    depends_on:
      - app_service
    volumes:
      # Masukkan konfigurasi Nginx kustom kita
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app_network

#--- VOLUMES AND NETWORKS ---
volumes:
  mysql_data: 
    driver: local

networks:
  app_network:
    driver: bridge