services:
  # --- 1. DATABASE SERVICE ---
  db_service:
    image: mysql:8.0
    # Nama container agar mudah dicek: db_D1_Kereta
    container_name: db_${GROUP_NAME} 
    restart: always
    environment:
      # Variabel ini WAJIB ada agar user 'sudo' otomatis dibuat saat pertama kali jalan
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}         # Mengambil 'sudo' dari .env
      MYSQL_PASSWORD: ${DB_PASS}     # Mengambil 'password123' dari .env
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      # [VOLUME 1] Data Persistence: Agar data tidak hilang saat docker direstart
      - mysql_data:/var/lib/mysql
      
      # [VOLUME 2] Init SQL: File ini akan dijalankan OTOMATIS saat database PERTAMA KALI dibuat
      # Pastikan folder di laptop bernama 'database' dan di dalamnya ada 'init.sql'
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 5s
      retries: 10
      start_period: 30s
    networks:
      - app_network

  # --- 2. APP SERVICE (Node.js) ---
  app_service:
    build: ./app
    container_name: app_${GROUP_NAME}
    restart: always
    expose:
      - "3000"
    environment:
      # KUNCI KONEKSI: DB_HOST harus diisi nama service database ('db_service')
      - DB_HOST=db_service
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_NAME=${DB_NAME}
      - APP_PORT=3000
    depends_on:
      db_service:
        condition: service_healthy
    volumes:
      # Mounting agar bisa edit codingan live tanpa rebuild terus menerus
      - ./app:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - app_network

  # --- 3. NGINX SERVICE ---
  nginx_service:
    image: nginx:alpine
    container_name: nginx_${GROUP_NAME}
    restart: always
    ports:
      # Mapping Port: Browser buka port 2584 (dari .env), diarahkan ke Nginx port 80
      - "${APP_PORT}:80"
    depends_on:
      - app_service
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app_network

# --- DEFINISI VOLUME & NETWORK ---
volumes:
  mysql_data: 
    driver: local

networks:
  app_network:
    driver: bridge